ACCEL_ASCII ""

(asciiHeader
  (asciiVersion 3 0)
  (timeStamp 2026 1 29 10 10 45)
  (program "Protel DXP" "Version 1.0.0.30000")
  (copyright "Copyright © Altium Limited 2015")
  (fileAuthor "")
  (headerString "")
  (fileUnits mil)
  (guidString "{00000000-0000-0000-0000-000000000000}")
)
(library "Library_1"
  (textStyleDef "(Default)"
    (font
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 100.0)
      (strokeWidth 10.0)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "(PinStyle)"
    (font
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 91.0)
      (strokeWidth 9.0)
    )
    (font
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Times New Roman")
      (fontHeight 139.0)
      (strokeWidth 0.19843 mm)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 7)
      (fontClipPrecision 32)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "(PartStyle)"
    (font
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 100.0)
      (strokeWidth 10.0)
    )
    (font
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Times New Roman")
      (fontHeight 139.0)
      (strokeWidth 0.19843 mm)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 7)
      (fontClipPrecision 32)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "(WireStyle)"
    (font
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 60.0)
      (strokeWidth 9.0)
    )
    (font
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Times New Roman")
      (fontHeight 139.0)
      (strokeWidth 0.19843 mm)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 7)
      (fontClipPrecision 32)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "(PortStyle)"
    (font
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 60.0)
      (strokeWidth 9.0)
    )
    (font
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Times New Roman")
      (fontHeight 139.0)
      (strokeWidth 0.19843 mm)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 7)
      (fontClipPrecision 32)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "(DefaultTTF)"
    (font
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 100.0)
      (strokeWidth 10.0)
    )
    (font
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Times New Roman")
      (fontHeight 139.0)
      (strokeWidth 0.19843 mm)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 7)
      (fontClipPrecision 32)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "10pTIMESNEWROMAN"
    (font
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Times New Roman")
      (fontHeight 139.0)
      (strokeWidth 0.19843 mm)
      (fontWeight 400)
      (fontItalic False)
      (fontCharSet 0)
      (fontOutPrecision 7)
      (fontClipPrecision 32)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (symbolDef "ESP32-H2-MINI-1-H2S_1_N"
    (originalName "ESP32-H2-MINI-1-H2S_1_N")
    (pin (pinNum 1)  (pt 200 0) (rotation 180.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 100 0) "1" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 200 0) "GND_1" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 2)  (pt 200 -100) (rotation 180.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 100 -100) "2" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 200 -100) "GND_2" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 3)  (pt 200 -200) (rotation 180.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 100 -200) "3" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 200 -200) "3V3" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 4)  (pt 200 -300) (rotation 180.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 100 -300) "4" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 200 -300) "NC_1" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 5)  (pt 200 -400) (rotation 180.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 100 -400) "5" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 200 -400) "IO2" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 6)  (pt 200 -500) (rotation 180.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 100 -500) "6" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 200 -500) "IO3" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 7)  (pt 200 -600) (rotation 180.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 100 -600) "7" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 200 -600) "NC_2" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 8)  (pt 200 -700) (rotation 180.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 100 -700) "8" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 200 -700) "EN" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 9)  (pt 200 -800) (rotation 180.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 100 -800) "9" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 200 -800) "IO0" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 10)  (pt 200 -900) (rotation 180.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 100 -900) "10" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 200 -900) "IO1" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 11)  (pt 200 -1000) (rotation 180.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 100 -1000) "11" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 200 -1000) "GND_3" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 12)  (pt 200 -1100) (rotation 180.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 100 -1100) "12" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 200 -1100) "IO13" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 13)  (pt 200 -1200) (rotation 180.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 100 -1200) "13" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 200 -1200) "IO14" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 14)  (pt 200 -1300) (rotation 180.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 100 -1300) "14" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 200 -1300) "GND_4" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 15)  (pt 200 -1400) (rotation 180.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 100 -1400) "15" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 200 -1400) "VBAT" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 16)  (pt 200 -1500) (rotation 180.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 100 -1500) "16" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 200 -1500) "IO12" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 17)  (pt 200 -1600) (rotation 180.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 100 -1600) "17" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 200 -1600) "NC_3" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 18)  (pt 200 -1700) (rotation 180.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 100 -1700) "18" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 200 -1700) "IO4" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 19)  (pt 200 -1800) (rotation 180.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 100 -1800) "19" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 200 -1800) "IO5" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 20)  (pt 200 -1900) (rotation 180.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 100 -1900) "20" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 200 -1900) "IO10" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 21)  (pt 200 -2000) (rotation 180.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 100 -2000) "21" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 200 -2000) "IO11" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 22)  (pt 200 -2100) (rotation 180.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 100 -2100) "22" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 200 -2100) "IO8" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 23)  (pt 200 -2200) (rotation 180.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 100 -2200) "23" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 200 -2200) "IO9" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 24)  (pt 200 -2300) (rotation 180.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 100 -2300) "24" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 200 -2300) "IO22" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 25)  (pt 200 -2400) (rotation 180.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 100 -2400) "25" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 200 -2400) "IO25" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 26)  (pt 200 -2500) (rotation 180.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 100 -2500) "26" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 200 -2500) "IO26" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 27)  (pt 200 -2600) (rotation 180.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 100 -2600) "27" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 200 -2600) "IO27" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 28)  (pt 200 -2700) (rotation 180.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 100 -2700) "28" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 200 -2700) "NC_4" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 29)  (pt 200 -2800) (rotation 180.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 100 -2800) "29" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 200 -2800) "NC_5" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 30)  (pt 200 -2900) (rotation 180.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 100 -2900) "30" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 200 -2900) "RXD0" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 31)  (pt 200 -3000) (rotation 180.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 100 -3000) "31" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 200 -3000) "TXD0" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 32)  (pt 1100 0) (rotation 0.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1200 0) "32" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1100 0) "NC_6" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 33)  (pt 1100 -100) (rotation 0.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1200 -100) "33" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1100 -100) "NC_7" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 34)  (pt 1100 -200) (rotation 0.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1200 -200) "34" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1100 -200) "NC_8" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 35)  (pt 1100 -300) (rotation 0.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1200 -300) "35" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1100 -300) "NC_9" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 36)  (pt 1100 -400) (rotation 0.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1200 -400) "36" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1100 -400) "GND_5" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 37)  (pt 1100 -500) (rotation 0.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1200 -500) "37" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1100 -500) "GND_6" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 38)  (pt 1100 -600) (rotation 0.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1200 -600) "38" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1100 -600) "GND_7" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 39)  (pt 1100 -700) (rotation 0.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1200 -700) "39" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1100 -700) "GND_8" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 40)  (pt 1100 -800) (rotation 0.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1200 -800) "40" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1100 -800) "GND_9" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 41)  (pt 1100 -900) (rotation 0.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1200 -900) "41" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1100 -900) "GND_10" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 42)  (pt 1100 -1000) (rotation 0.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1200 -1000) "42" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1100 -1000) "GND_11" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 43)  (pt 1100 -1100) (rotation 0.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1200 -1100) "43" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1100 -1100) "GND_12" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 44)  (pt 1100 -1200) (rotation 0.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1200 -1200) "44" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1100 -1200) "GND_13" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 45)  (pt 1100 -1300) (rotation 0.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1200 -1300) "45" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1100 -1300) "GND_14" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 46)  (pt 1100 -1400) (rotation 0.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1200 -1400) "46" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1100 -1400) "GND_15" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 47)  (pt 1100 -1500) (rotation 0.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1200 -1500) "47" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1100 -1500) "GND_16" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 48)  (pt 1100 -1600) (rotation 0.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1200 -1600) "48" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1100 -1600) "GND_17" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 49)  (pt 1100 -1700) (rotation 0.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1200 -1700) "49" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1100 -1700) "GND_18" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 50)  (pt 1100 -1800) (rotation 0.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1200 -1800) "50" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1100 -1800) "GND_19" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 51)  (pt 1100 -1900) (rotation 0.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1200 -1900) "51" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1100 -1900) "GND_20" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 52)  (pt 1100 -2000) (rotation 0.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1200 -2000) "52" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1100 -2000) "GND_21" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 53)  (pt 1100 -2100) (rotation 0.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1200 -2100) "53" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1100 -2100) "GND_22" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 54)  (pt 1100 -2200) (rotation 0.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1200 -2200) "54" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1100 -2200) "GND_23" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 55)  (pt 1100 -2300) (rotation 0.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1200 -2300) "55" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1100 -2300) "GND_24" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 56)  (pt 1100 -2400) (rotation 0.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1200 -2400) "56" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1100 -2400) "GND_25" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 57)  (pt 1100 -2500) (rotation 0.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1200 -2500) "57" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1100 -2500) "GND_26" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 58)  (pt 1100 -2600) (rotation 0.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1200 -2600) "58" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1100 -2600) "GND_27" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 59)  (pt 1100 -2700) (rotation 0.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1200 -2700) "59" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1100 -2700) "GND_28" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 60)  (pt 1100 -2800) (rotation 0.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1200 -2800) "60" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1100 -2800) "GND_29" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 61)  (pt 1100 -2900) (rotation 0.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1200 -2900) "61" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1100 -2900) "GND_30" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (line (pt 200 -3100) (pt 200 100) (width 10) )
    (line (pt 200 -3100) (pt 1100 -3100) (width 10) )
    (line (pt 200 100) (pt 1100 100) (width 10) )
    (line (pt 1100 100) (pt 1100 -3100) (width 10) )
    (attr "RefDes" ""  (pt 200 100) (isVisible True) (justify LowerLeft) (textStyleRef "(PartStyle)") )
    (attr "Type" ""  (pt 200 -3200) (isVisible False) (justify LowerLeft) (textStyleRef "(PartStyle)") )
    (attr "Mouser Part Number" "*"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "Mouser Price/Stock" "*"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "Manufacturer_Name" "Espressif Systems"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "Manufacturer_Part_F7" "ESP32-H2-MINI-1-H2S"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "Datasheet Link" "https://documentation.espressif.com/api/resource/doc/file/nzV9jBYD/FILE/esp32-h2-mini-1_mini-1u_datasheet_en.pdf"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "Geometry.Height" "2.55mm"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "Comment" "ESP32-H2-MINI-1-H2S"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
  )
  (symbolDef "GND_1_N"
    (originalName "GND_1_N")
    (pin (pinNum 1)  (pt 100 0) (rotation 180.0) (isFlipped False) (pinLength 100)
      (pinDisplay (dispPinDes False) (dispPinName False) )
      (pinDes    (text  (pt 50 0) "1" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 100 0) "GND" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (line (pt 110 100) (pt 110 -100) (width 15) )
    (line (pt 140 70) (pt 140 -70) (width 15) )
    (line (pt 170 40) (pt 170 -40) (width 15) )
    (line (pt 200 10) (pt 200 -10) (width 15) )
    (attr "Type" ""  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "RefDes" ""  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "Value" ""  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
  )
  (compDef "ESP32-H2-MINI-1-H2S"
    (originalName "ESP32-H2-MINI-1-H2S")
    (compHeader
      (sourceLibrary "")
      (compType Normal)
      (numPins 61)
      (numParts 1)
      (composition Homogeneous)
      (alts (ieeeAlt False) (deMorganAlt False) )
      (refDesPrefix "U")
    )
    (compPin "1" (pinName "GND_1") (partNum 1) (symPinNum 1) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "2" (pinName "GND_2") (partNum 1) (symPinNum 2) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "3" (pinName "3V3") (partNum 1) (symPinNum 3) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "4" (pinName "NC_1") (partNum 1) (symPinNum 4) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "5" (pinName "IO2") (partNum 1) (symPinNum 5) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "6" (pinName "IO3") (partNum 1) (symPinNum 6) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "7" (pinName "NC_2") (partNum 1) (symPinNum 7) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "8" (pinName "EN") (partNum 1) (symPinNum 8) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "9" (pinName "IO0") (partNum 1) (symPinNum 9) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "10" (pinName "IO1") (partNum 1) (symPinNum 10) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "11" (pinName "GND_3") (partNum 1) (symPinNum 11) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "12" (pinName "IO13") (partNum 1) (symPinNum 12) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "13" (pinName "IO14") (partNum 1) (symPinNum 13) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "14" (pinName "GND_4") (partNum 1) (symPinNum 14) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "15" (pinName "VBAT") (partNum 1) (symPinNum 15) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "16" (pinName "IO12") (partNum 1) (symPinNum 16) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "17" (pinName "NC_3") (partNum 1) (symPinNum 17) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "18" (pinName "IO4") (partNum 1) (symPinNum 18) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "19" (pinName "IO5") (partNum 1) (symPinNum 19) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "20" (pinName "IO10") (partNum 1) (symPinNum 20) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "21" (pinName "IO11") (partNum 1) (symPinNum 21) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "22" (pinName "IO8") (partNum 1) (symPinNum 22) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "23" (pinName "IO9") (partNum 1) (symPinNum 23) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "24" (pinName "IO22") (partNum 1) (symPinNum 24) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "25" (pinName "IO25") (partNum 1) (symPinNum 25) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "26" (pinName "IO26") (partNum 1) (symPinNum 26) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "27" (pinName "IO27") (partNum 1) (symPinNum 27) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "28" (pinName "NC_4") (partNum 1) (symPinNum 28) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "29" (pinName "NC_5") (partNum 1) (symPinNum 29) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "30" (pinName "RXD0") (partNum 1) (symPinNum 30) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "31" (pinName "TXD0") (partNum 1) (symPinNum 31) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "32" (pinName "NC_6") (partNum 1) (symPinNum 32) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "33" (pinName "NC_7") (partNum 1) (symPinNum 33) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "34" (pinName "NC_8") (partNum 1) (symPinNum 34) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "35" (pinName "NC_9") (partNum 1) (symPinNum 35) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "36" (pinName "GND_5") (partNum 1) (symPinNum 36) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "37" (pinName "GND_6") (partNum 1) (symPinNum 37) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "38" (pinName "GND_7") (partNum 1) (symPinNum 38) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "39" (pinName "GND_8") (partNum 1) (symPinNum 39) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "40" (pinName "GND_9") (partNum 1) (symPinNum 40) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "41" (pinName "GND_10") (partNum 1) (symPinNum 41) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "42" (pinName "GND_11") (partNum 1) (symPinNum 42) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "43" (pinName "GND_12") (partNum 1) (symPinNum 43) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "44" (pinName "GND_13") (partNum 1) (symPinNum 44) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "45" (pinName "GND_14") (partNum 1) (symPinNum 45) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "46" (pinName "GND_15") (partNum 1) (symPinNum 46) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "47" (pinName "GND_16") (partNum 1) (symPinNum 47) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "48" (pinName "GND_17") (partNum 1) (symPinNum 48) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "49" (pinName "GND_18") (partNum 1) (symPinNum 49) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "50" (pinName "GND_19") (partNum 1) (symPinNum 50) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "51" (pinName "GND_20") (partNum 1) (symPinNum 51) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "52" (pinName "GND_21") (partNum 1) (symPinNum 52) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "53" (pinName "GND_22") (partNum 1) (symPinNum 53) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "54" (pinName "GND_23") (partNum 1) (symPinNum 54) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "55" (pinName "GND_24") (partNum 1) (symPinNum 55) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "56" (pinName "GND_25") (partNum 1) (symPinNum 56) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "57" (pinName "GND_26") (partNum 1) (symPinNum 57) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "58" (pinName "GND_27") (partNum 1) (symPinNum 58) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "59" (pinName "GND_28") (partNum 1) (symPinNum 59) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "60" (pinName "GND_29") (partNum 1) (symPinNum 60) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "61" (pinName "GND_30") (partNum 1) (symPinNum 61) (gateEq 0) (pinEq 0) (pinType Passive) )
    (attachedSymbol (partNum 1) (altType Normal) (symbolName "ESP32-H2-MINI-1-H2S_1_N") )
    (attachedPattern (patternNum 1) (patternName "ESP32H2MINI1H2S")
      (numPads 61)
      (padPinMap
        (padNum  1) (compPinRef "1")
        (padNum  2) (compPinRef "2")
        (padNum  3) (compPinRef "3")
        (padNum  4) (compPinRef "4")
        (padNum  5) (compPinRef "5")
        (padNum  6) (compPinRef "6")
        (padNum  7) (compPinRef "7")
        (padNum  8) (compPinRef "8")
        (padNum  9) (compPinRef "9")
        (padNum  10) (compPinRef "10")
        (padNum  11) (compPinRef "11")
        (padNum  12) (compPinRef "12")
        (padNum  13) (compPinRef "13")
        (padNum  14) (compPinRef "14")
        (padNum  15) (compPinRef "15")
        (padNum  16) (compPinRef "16")
        (padNum  17) (compPinRef "17")
        (padNum  18) (compPinRef "18")
        (padNum  19) (compPinRef "19")
        (padNum  20) (compPinRef "20")
        (padNum  21) (compPinRef "21")
        (padNum  22) (compPinRef "22")
        (padNum  23) (compPinRef "23")
        (padNum  24) (compPinRef "24")
        (padNum  25) (compPinRef "25")
        (padNum  26) (compPinRef "26")
        (padNum  27) (compPinRef "27")
        (padNum  28) (compPinRef "28")
        (padNum  29) (compPinRef "29")
        (padNum  30) (compPinRef "30")
        (padNum  31) (compPinRef "31")
        (padNum  32) (compPinRef "32")
        (padNum  33) (compPinRef "33")
        (padNum  34) (compPinRef "34")
        (padNum  35) (compPinRef "35")
        (padNum  36) (compPinRef "36")
        (padNum  37) (compPinRef "37")
        (padNum  38) (compPinRef "38")
        (padNum  39) (compPinRef "39")
        (padNum  40) (compPinRef "40")
        (padNum  41) (compPinRef "41")
        (padNum  42) (compPinRef "42")
        (padNum  43) (compPinRef "43")
        (padNum  44) (compPinRef "44")
        (padNum  45) (compPinRef "45")
        (padNum  46) (compPinRef "46")
        (padNum  47) (compPinRef "47")
        (padNum  48) (compPinRef "48")
        (padNum  49) (compPinRef "49")
        (padNum  50) (compPinRef "50")
        (padNum  51) (compPinRef "51")
        (padNum  52) (compPinRef "52")
        (padNum  53) (compPinRef "53")
        (padNum  54) (compPinRef "54")
        (padNum  55) (compPinRef "55")
        (padNum  56) (compPinRef "56")
        (padNum  57) (compPinRef "57")
        (padNum  58) (compPinRef "58")
        (padNum  59) (compPinRef "59")
        (padNum  60) (compPinRef "60")
        (padNum  61) (compPinRef "61")
      )
    )
  )
  (compDef "GND"
    (originalName "GND")
    (compHeader
      (sourceLibrary "")
      (compType Power)
      (numPins 1)
      (numParts 1)
      (refDesPrefix "P")
    )
    (compPin "1" (pinName "GND") (partNum 1) (symPinNum 1) (gateEq 1) (pinEq 0) (pinType Power))
    (attachedSymbol (partNum 1) (altType Normal) (symbolName "GND_1_N") )
  )
)

(netlist "Netlist_1"
  (compInst "B?"
    (compRef "ESP32-H2-MINI-1-H2S")
    (originalName "ESP32-H2-MINI-1-H2S")
    (patternName "ESP32H2MINI1H2S")
    (attr "Datasheet Link" "https://documentation.espressif.com/api/resource/doc/file/nzV9jBYD/FILE/esp32-h2-mini-1_mini-1u_datasheet_en.pdf" (textStyleRef "(Default)") (constraintUnits string))
    (attr "Geometry.Height" "2.55mm" (textStyleRef "(Default)") (constraintUnits string))
    (attr "Manufacturer_Name" "Espressif Systems" (textStyleRef "(Default)") (constraintUnits string))
    (attr "Manufacturer_Part_F7" "ESP32-H2-MINI-1-H2S" (textStyleRef "(Default)") (constraintUnits string))
    (attr "Mouser Part Number" "" (textStyleRef "(Default)") (constraintUnits string))
    (attr "Mouser Price/Stock" "" (textStyleRef "(Default)") (constraintUnits string))
  )
  (compInst "C?"
    (compRef "CAPACITOR")
    (originalName "Capacitor")
    (compValue "1u")
    (attr "CPAR" "" (pt -90 320) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "LSER" "" (pt -90 320) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "RLSHUNT" "" (pt -90 320) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "RPAR" "" (pt -90 320) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "RSER" "" (pt -90 320) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "SimulationGenericCE9" "True" (pt -90 320) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "TEMP" "" (pt -90 320) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
  )
  (compInst "C?"
    (compRef "CAPACITOR")
    (originalName "Capacitor")
    (compValue "0.1u")
    (attr "CPAR" "" (pt -90 320) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "LSER" "" (pt -90 320) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "RLSHUNT" "" (pt -90 320) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "RPAR" "" (pt -90 320) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "RSER" "" (pt -90 320) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "SimulationGenericCE9" "True" (pt -90 320) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "TEMP" "" (pt -90 320) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
  )
  (compInst "C?"
    (compRef "CAPACITOR")
    (originalName "Capacitor")
    (compValue "0.1u")
    (attr "CPAR" "" (pt -90 320) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "LSER" "" (pt -90 320) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "RLSHUNT" "" (pt -90 320) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "RPAR" "" (pt -90 320) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "RSER" "" (pt -90 320) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "SimulationGenericCE9" "True" (pt -90 320) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "TEMP" "" (pt -90 320) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
  )
  (compInst "C?"
    (compRef "CAPACITOR")
    (originalName "Capacitor")
    (compValue "0.1u")
    (attr "CPAR" "" (pt -90 20) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "LSER" "" (pt -90 20) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "RLSHUNT" "" (pt -90 20) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "RPAR" "" (pt -90 20) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "RSER" "" (pt -90 20) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "SimulationGenericCE9" "True" (pt -90 20) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "TEMP" "" (pt -90 20) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
  )
  (compInst "C?"
    (compRef "CAPACITOR")
    (originalName "Capacitor")
    (compValue "10u")
    (attr "CPAR" "" (pt -90 320) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "LSER" "" (pt -90 320) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "RLSHUNT" "" (pt -90 320) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "RPAR" "" (pt -90 320) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "RSER" "" (pt -90 320) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "SimulationGenericCE9" "True" (pt -90 320) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "TEMP" "" (pt -90 320) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
  )
  (compInst "J?"
    (compRef "691137710002")
    (originalName "691137710002")
    (patternName "SHDR2W70P0X500_1X2_1000X750XB8")
    (attr "Datasheet Link" "https://www.we-online.com/components/products/download/691137710002+%28rev1%29.pdf" (pt -600 100) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Geometry.Height" "11.5mm" (pt -600 100) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Manufacturer_Name" "Wurth Elektronik" (pt -600 100) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Manufacturer_Part_F7" "691137710002" (pt -600 100) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Mouser Part Number" "710-691137710002" (pt -600 100) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Mouser Price/Stock" "https://www.mouser.co.uk/ProductDetail/Wurth-Elektronik/691137710002?qs=lBTPRtX1sU9LnHBbviNKGA%3D%3D" (pt -600 100) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
  )
  (compInst "J?"
    (compRef "691137710002")
    (originalName "691137710002")
    (patternName "SHDR2W70P0X500_1X2_1000X750XB8")
    (attr "Datasheet Link" "https://www.we-online.com/components/products/download/691137710002+%28rev1%29.pdf" (pt -600 100) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Geometry.Height" "11.5mm" (pt -600 100) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Manufacturer_Name" "Wurth Elektronik" (pt -600 100) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Manufacturer_Part_F7" "691137710002" (pt -600 100) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Mouser Part Number" "710-691137710002" (pt -600 100) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Mouser Price/Stock" "https://www.mouser.co.uk/ProductDetail/Wurth-Elektronik/691137710002?qs=lBTPRtX1sU9LnHBbviNKGA%3D%3D" (pt -600 100) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
  )
  (compInst "R?"
    (compRef "RESISTOR")
    (originalName "Resistor")
    (compValue "10K")
    (attr "DTEMP" "" (pt -30 420) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "SimulationGenericCE9" "True" (pt -30 420) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "T_REL_LOCAL" "" (pt -30 420) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "TC" "" (pt -30 420) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "TC1" "0" (pt -30 420) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "TC2" "0" (pt -30 420) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "TEMP" "" (pt -30 420) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
  )
  (compInst "R?"
    (compRef "RESISTOR")
    (originalName "Resistor")
    (compValue "10K")
    (attr "DTEMP" "" (pt -30 420) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "SimulationGenericCE9" "True" (pt -30 420) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "T_REL_LOCAL" "" (pt -30 420) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "TC" "" (pt -30 420) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "TC1" "0" (pt -30 420) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "TC2" "0" (pt -30 420) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "TEMP" "" (pt -30 420) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
  )
  (compInst "X?"
    (compRef "TS02-66-43-BK-100-LCR-D")
    (originalName "TS02-66-43-BK-100-LCR-D")
    (patternName "TS026643BK100LCRD")
    (attr "Datasheet Link" "https://www.sameskydevices.com/product/resource/TS02-66-43-BK-100-LCR-D.pdf" (textStyleRef "(Default)") (constraintUnits string))
    (attr "Geometry.Height" "4.5mm" (textStyleRef "(Default)") (constraintUnits string))
    (attr "Manufacturer_Name" "Same Sky" (textStyleRef "(Default)") (constraintUnits string))
    (attr "Manufacturer_Part_F7" "TS02-66-43-BK-100-LCR-D" (textStyleRef "(Default)") (constraintUnits string))
    (attr "Mouser Part Number" "179-TS026643BK100LCR" (textStyleRef "(Default)") (constraintUnits string))
    (attr "Mouser Price/Stock" "https://www.mouser.co.uk/ProductDetail/Same-Sky/TS02-66-43-BK-100-LCR-D?qs=A6eO%252BMLsxmQKx8LKBmCQ6w%3D%3D" (textStyleRef "(Default)") (constraintUnits string))
  )
  (compInst "X?"
    (compRef "TS02-66-43-BK-100-LCR-D")
    (originalName "TS02-66-43-BK-100-LCR-D")
    (patternName "TS026643BK100LCRD")
    (attr "Datasheet Link" "https://www.sameskydevices.com/product/resource/TS02-66-43-BK-100-LCR-D.pdf" (pt -20 100) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Geometry.Height" "4.5mm" (pt -20 100) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Manufacturer_Name" "Same Sky" (pt -20 100) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Manufacturer_Part_F7" "TS02-66-43-BK-100-LCR-D" (pt -20 100) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Mouser Part Number" "179-TS026643BK100LCR" (pt -20 100) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Mouser Price/Stock" "https://www.mouser.co.uk/ProductDetail/Same-Sky/TS02-66-43-BK-100-LCR-D?qs=A6eO%252BMLsxmQKx8LKBmCQ6w%3D%3D" (pt -20 100) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
  )
  (compInst "GND1"
    (compRef "GND")
    (originalName "GND")
  )
  (compInst "GND2"
    (compRef "GND")
    (originalName "GND")
  )
  (compInst "GND3"
    (compRef "GND")
    (originalName "GND")
  )
  (compInst "GND4"
    (compRef "GND")
    (originalName "GND")
  )
  (compInst "GND5"
    (compRef "GND")
    (originalName "GND")
  )
  (compInst "GND6"
    (compRef "GND")
    (originalName "GND")
  )
  (compInst "GND7"
    (compRef "GND")
    (originalName "GND")
  )
  (net "GND"
    (node "B?" "1")
    (node "B?" "2")
    (node "B?" "36")
    (node "B?" "37")
    (node "B?" "38")
    (node "B?" "39")
    (node "B?" "40")
    (node "B?" "41")
    (node "B?" "42")
    (node "B?" "43")
    (node "B?" "44")
    (node "B?" "45")
    (node "B?" "46")
    (node "B?" "47")
    (node "B?" "48")
    (node "B?" "49")
    (node "B?" "50")
    (node "B?" "51")
    (node "B?" "52")
    (node "B?" "53")
    (node "B?" "54")
    (node "B?" "55")
    (node "B?" "56")
    (node "B?" "57")
    (node "B?" "58")
    (node "B?" "59")
    (node "B?" "60")
    (node "B?" "61")
    (node "C?" "1")
    (node "C?" "1")
    (node "C?" "1")
    (node "C?" "1")
    (node "C?" "2")
    (node "J?" "2")
    (node "X?" "1")
    (node "X?" "1")
    (node "X?" "3")
    (node "GND1" "1")
    (node "GND2" "1")
    (node "GND3" "1")
    (node "GND4" "1")
    (node "GND5" "1")
    (node "GND6" "1")
    (node "GND7" "1")
  )
  (net "NetB?_23"
    (node "B?" "23")
    (node "C?" "2")
    (node "X?" "4")
  )
  (net "NetB?_3"
    (node "B?" "3")
    (node "C?" "1")
    (node "C?" "2")
    (node "J?" "1")
    (node "R?" "1")
    (node "R?" "2")
  )
  (net "NetB?_30"
    (node "B?" "30")
    (node "J?" "1")
  )
  (net "NetB?_31"
    (node "B?" "31")
    (node "J?" "2")
  )
  (net "NetB?_8"
    (node "B?" "8")
    (node "C?" "2")
    (node "C?" "2")
    (node "R?" "1")
    (node "X?" "4")
  )
  (net "NetR?_2"
    (node "R?" "2")
  )
)

(schematicDesign "SchDesign_1"
  (schDesignHeader
    (workspaceSize 180000 180000)
    (gridDfns
      (grid "100mil")
    )
    (designInfo
      (fieldSet "(Default)"
        (fieldDef "Time" "")
        (fieldDef "Date" "")
        (fieldDef "Approved By" "")
        (fieldDef "Checked By" "")
        (fieldDef "Author" "")
        (fieldDef "Company Name" "")
        (fieldDef "Drawn By" "")
        (fieldDef "Engineer" "")
        (fieldDef "Organization" "")
        (fieldDef "Address1" "")
        (fieldDef "Address2" "")
        (fieldDef "Address3" "")
        (fieldDef "Address4" "")
        (fieldDef "Title" "")
        (fieldDef "Drawing Number" "")
        (fieldDef "Revision" "")
        (fieldDef "Rule" "")
        (fieldDef "ImagePath" "")
        (fieldDef "ProjectName" "")
        (fieldDef "Application_BuildNumber" "")
      )
    )
    (refPointSize 100)
    (infoPointSize 100)
    (junctionSize 20)
    (refPointSizePrint 100)
    (infoPointSizePrint 100)
    (junctionSizePrint 20)
  )

  (sheet "Sheet1" (sheetNum 1)
    (titleSheet ""
      1.0000
      (isVisible True)
      (offset 0.0 0.0)
      (border
        (isVisible True)
        (height 7500)
        (width 9500)
        (offset 0 0)
      )
      (zones
        (isVisible True)
        (textStyleRef "(Default)")
        (horizontalZones 4
          (numDirection ascending)
          (numType Alphabetic)
        )
        (verticalZones 4
          (numDirection ascending)
          (numType Numeric)
        )
      )
    )
    (fieldSetRef "(Default)")
    (wire (line (pt 3100 6000) (pt 3400 6000) (width 10) (netNameRef "NetR?_2") )
    )
    (wire (line (pt 3800 2400) (pt 4100 2400) (width 10) (netNameRef "NetB?_31") )
    )
    (wire (line (pt 4100 2500) (pt 3800 2500) (width 10) (netNameRef "NetB?_30") )
    )
    (wire (line (pt 4100 3200) (pt 2500 3200) (width 10) (netNameRef "NetB?_23") )
    )
    (wire (line (pt 2500 3200) (pt 2300 3200) (width 10) (netNameRef "NetB?_23") )
    )
    (wire (line (pt 1800 4700) (pt 2200 4700) (width 10) (netNameRef "NetB?_8") )
    )
    (wire (line (pt 2200 4700) (pt 2400 4700) (width 10) (netNameRef "NetB?_8") )
    )
    (wire (line (pt 2400 4700) (pt 2700 4700) (width 10) (netNameRef "NetB?_8") )
    )
    (wire (line (pt 2700 4700) (pt 3100 4700) (width 10) (netNameRef "NetB?_8") )
    )
    (wire (line (pt 3100 4700) (pt 4100 4700) (width 10) (netNameRef "NetB?_8") )
    )
    (wire (line (pt 3100 5200) (pt 3100 4700) (width 10) (netNameRef "NetB?_8") )
    )
    (wire (line (pt 1600 5600) (pt 2100 5600) (width 10) (netNameRef "NetB?_3") )
    )
    (wire (line (pt 2500 5600) (pt 2100 5600) (width 10) (netNameRef "NetB?_3") )
    )
    (wire (line (pt 2500 5600) (pt 3100 5600) (width 10) (netNameRef "NetB?_3") )
    )
    (wire (line (pt 3100 5600) (pt 3500 5600) (width 10) (netNameRef "NetB?_3") )
    )
    (wire (line (pt 3500 5600) (pt 3500 5200) (width 10) (netNameRef "NetB?_3") )
    )
    (wire (line (pt 3500 5200) (pt 4100 5200) (width 10) (netNameRef "NetB?_3") )
    )
    (wire (line (pt 1100 3300) (pt 1000 3300) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 1000 3300) (pt 1000 2900) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 1000 2900) (pt 1000 2800) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 2500 2900) (pt 1000 2900) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 1000 4400) (pt 1000 4700) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 1000 4700) (pt 1000 4800) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 1000 4400) (pt 2400 4400) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 1600 5500) (pt 1700 5500) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 4100 5300) (pt 4100 5400) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 4100 5400) (pt 4100 5700) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 4100 5700) (pt 5600 5700) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 5600 5700) (pt 5600 5000) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 5400 2500) (pt 5600 2500) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 5600 2500) (pt 5600 2400) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 5400 2600) (pt 5600 2600) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 5600 2600) (pt 5600 2500) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 5400 2700) (pt 5600 2700) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 5600 2700) (pt 5600 2600) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 5400 2800) (pt 5600 2800) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 5600 2800) (pt 5600 2700) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 5400 2900) (pt 5600 2900) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 5600 2900) (pt 5600 2800) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 5400 3000) (pt 5600 3000) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 5600 3000) (pt 5600 2900) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 5400 3100) (pt 5600 3100) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 5600 3100) (pt 5600 3000) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 5400 3200) (pt 5600 3200) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 5600 3200) (pt 5600 3100) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 5400 3300) (pt 5600 3300) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 5600 3300) (pt 5600 3200) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 5400 3400) (pt 5600 3400) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 5600 3400) (pt 5600 3300) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 5400 3500) (pt 5600 3500) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 5600 3500) (pt 5600 3400) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 5400 3600) (pt 5600 3600) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 5600 3600) (pt 5600 3500) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 5400 3700) (pt 5600 3700) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 5600 3700) (pt 5600 3600) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 5400 3800) (pt 5600 3800) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 5600 3800) (pt 5600 3700) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 5400 3900) (pt 5600 3900) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 5600 3900) (pt 5600 3800) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 5400 4000) (pt 5600 4000) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 5600 4000) (pt 5600 3900) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 5400 4100) (pt 5600 4100) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 5600 4100) (pt 5600 4000) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 5400 4200) (pt 5600 4200) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 5600 4200) (pt 5600 4100) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 5400 4300) (pt 5600 4300) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 5600 4300) (pt 5600 4200) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 5400 4400) (pt 5600 4400) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 5600 4400) (pt 5600 4300) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 5400 4500) (pt 5600 4500) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 5600 4500) (pt 5600 4400) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 5400 4600) (pt 5600 4600) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 5600 4600) (pt 5600 4500) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 5400 4700) (pt 5600 4700) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 5600 4700) (pt 5600 4600) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 5400 4800) (pt 5600 4800) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 5600 4800) (pt 5600 4700) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 5400 4900) (pt 5600 4900) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 5600 4900) (pt 5600 4800) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 5400 5000) (pt 5600 5000) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 5600 5000) (pt 5600 4900) (width 10) (netNameRef "GND") )
    )
    (port (pt 3400 6000) (portType NoAngle_Sgl_Horz) (portPinLength PortPinLong) (netNameRef "NetR?_2")  )
    (port (pt 3800 3300) (portType NoAngle_Sgl_Horz) (portPinLength PortPinLong) (netNameRef "NetR?_2")  )
    (symbol (symbolRef "ESP32-H2-MINI-1-H2S_1_N") (refDesRef "B?") (partNum 1) (pt 4100 5400)
      (attr "RefDes" "B?" (pt 200 100) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Manufacturer_Name" "Espressif Systems" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Manufacturer_Part_F7" "ESP32-H2-MINI-1-H2S" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Datasheet Link" "https://documentation.espressif.com/api/resource/doc/file/nzV9jBYD/FILE/esp32-h2-mini-1_mini-1u_datasheet_en.pdf" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Geometry.Height" "2.55mm" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Comment" "ESP32-H2-MINI-1-H2S" (pt 200 -3200) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
    )
    (symbol (symbolRef "691137710002_1_N") (refDesRef "J?") (partNum 1) (pt 3800 2500) (isFlipped True)
      (attr "RefDes" "J?" (pt -600 100) (isFlipped true) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Mouser Part Number" "710-691137710002" (pt -600 100) (isFlipped true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Mouser Price/Stock" "https://www.mouser.co.uk/ProductDetail/Wurth-Elektronik/691137710002?qs=lBTPRtX1sU9LnHBbviNKGA%3D%3D" (pt -600 100) (isFlipped true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Manufacturer_Name" "Wurth Elektronik" (pt -600 100) (isFlipped true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Manufacturer_Part_F7" "691137710002" (pt -600 100) (isFlipped true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Datasheet Link" "https://www.we-online.com/components/products/download/691137710002+%28rev1%29.pdf" (pt -600 100) (isFlipped true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Geometry.Height" "11.5mm" (pt -600 100) (isFlipped true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Comment" "691137710002" (pt -600 -300) (isFlipped true) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
    )
    (symbol (symbolRef "GND_1_N") (refDesRef "GND1") (partNum 1) (pt 5600 2400) (rotation 270.0) )
    (symbol (symbolRef "691137710002_1_N") (refDesRef "J?") (partNum 1) (pt 1600 5600) (isFlipped True)
      (attr "RefDes" "J?" (pt -600 100) (isFlipped true) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Mouser Part Number" "710-691137710002" (pt -600 100) (isFlipped true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Mouser Price/Stock" "https://www.mouser.co.uk/ProductDetail/Wurth-Elektronik/691137710002?qs=lBTPRtX1sU9LnHBbviNKGA%3D%3D" (pt -600 100) (isFlipped true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Manufacturer_Name" "Wurth Elektronik" (pt -600 100) (isFlipped true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Manufacturer_Part_F7" "691137710002" (pt -600 100) (isFlipped true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Datasheet Link" "https://www.we-online.com/components/products/download/691137710002+%28rev1%29.pdf" (pt -600 100) (isFlipped true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Geometry.Height" "11.5mm" (pt -600 100) (isFlipped true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Comment" "691137710002" (pt -600 -300) (isFlipped true) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
    )
    (symbol (symbolRef "Capacitor_1_N") (refDesRef "C?") (partNum 1) (pt 2100 5300) (rotation 90.0)
      (attr "RefDes" "C?" (pt 90 110) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "SimulationGenericCE9" "True" (pt -90 320) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Value" "10u" (pt 90 10) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Comment" "Capacitor" (pt -90 320) (textStyleRef "(PartStyle)") (constraintUnits string) )
    )
    (symbol (symbolRef "Capacitor_1_N") (refDesRef "C?") (partNum 1) (pt 2500 5600) (rotation 270.0) (isFlipped True)
      (attr "RefDes" "C?" (pt 90 -190) (isFlipped true) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "SimulationGenericCE9" "True" (pt -90 20) (isFlipped true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Value" "0.1u" (pt 90 -290) (isFlipped true) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Comment" "Capacitor" (pt -90 20) (isFlipped true) (textStyleRef "(PartStyle)") (constraintUnits string) )
    )
    (symbol (symbolRef "GND_1_N") (refDesRef "GND2") (partNum 1) (pt 2100 5300) (rotation 270.0) )
    (symbol (symbolRef "GND_1_N") (refDesRef "GND3") (partNum 1) (pt 2500 5300) (rotation 270.0) )
    (symbol (symbolRef "GND_1_N") (refDesRef "GND4") (partNum 1) (pt 1700 5500) (rotation 270.0) )
    (symbol (symbolRef "Resistor_1_N") (refDesRef "R?") (partNum 1) (pt 3100 5200) (rotation 90.0)
      (attr "RefDes" "R?" (pt 30 210) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "TC1" "0" (pt -30 420) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "TC2" "0" (pt -30 420) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "SimulationGenericCE9" "True" (pt -30 420) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Value" "10K" (pt 30 110) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Comment" "Resistor" (pt -30 420) (textStyleRef "(PartStyle)") (constraintUnits string) )
    )
    (symbol (symbolRef "TS02-66-43-BK-100-LCR-D_1_N") (refDesRef "X?") (partNum 1) (pt 1000 4800)
      (attr "RefDes" "X?" (pt 200 100) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Mouser Part Number" "179-TS026643BK100LCR" (pt -20 100) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Mouser Price/Stock" "https://www.mouser.co.uk/ProductDetail/Same-Sky/TS02-66-43-BK-100-LCR-D?qs=A6eO%252BMLsxmQKx8LKBmCQ6w%3D%3D" (pt -20 100) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Manufacturer_Name" "Same Sky" (pt -20 100) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Manufacturer_Part_F7" "TS02-66-43-BK-100-LCR-D" (pt -20 100) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Datasheet Link" "https://www.sameskydevices.com/product/resource/TS02-66-43-BK-100-LCR-D.pdf" (pt -20 100) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Geometry.Height" "4.5mm" (pt -20 100) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Comment" "TS02-66-43-BK-100-LCR-D" (pt 200 -300) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
    )
    (symbol (symbolRef "TS02-66-43-BK-100-LCR-D_1_N") (refDesRef "X?") (partNum 1) (pt 1100 3300)
      (attr "RefDes" "X?" (pt 200 100) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Mouser Part Number" "179-TS026643BK100LCR" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Mouser Price/Stock" "https://www.mouser.co.uk/ProductDetail/Same-Sky/TS02-66-43-BK-100-LCR-D?qs=A6eO%252BMLsxmQKx8LKBmCQ6w%3D%3D" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Manufacturer_Name" "Same Sky" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Manufacturer_Part_F7" "TS02-66-43-BK-100-LCR-D" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Datasheet Link" "https://www.sameskydevices.com/product/resource/TS02-66-43-BK-100-LCR-D.pdf" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Geometry.Height" "4.5mm" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Comment" "TS02-66-43-BK-100-LCR-D" (pt 200 -300) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
    )
    (symbol (symbolRef "Capacitor_1_N") (refDesRef "C?") (partNum 1) (pt 2500 2900) (rotation 90.0)
      (attr "RefDes" "C?" (pt 90 110) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "SimulationGenericCE9" "True" (pt -90 320) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Value" "0.1u" (pt 90 10) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Comment" "Capacitor" (pt -90 320) (textStyleRef "(PartStyle)") (constraintUnits string) )
    )
    (symbol (symbolRef "GND_1_N") (refDesRef "GND5") (partNum 1) (pt 1000 2800) (rotation 270.0) )
    (symbol (symbolRef "Capacitor_1_N") (refDesRef "C?") (partNum 1) (pt 2400 4400) (rotation 90.0)
      (attr "RefDes" "C?" (pt 90 110) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "SimulationGenericCE9" "True" (pt -90 320) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Value" "0.1u" (pt 90 10) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Comment" "Capacitor" (pt -90 320) (textStyleRef "(PartStyle)") (constraintUnits string) )
    )
    (symbol (symbolRef "Capacitor_1_N") (refDesRef "C?") (partNum 1) (pt 2700 4400) (rotation 90.0)
      (attr "RefDes" "C?" (pt 90 110) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "SimulationGenericCE9" "True" (pt -90 320) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Value" "1u" (pt 90 10) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Comment" "Capacitor" (pt -90 320) (textStyleRef "(PartStyle)") (constraintUnits string) )
    )
    (symbol (symbolRef "GND_1_N") (refDesRef "GND6") (partNum 1) (pt 2700 4400) (rotation 270.0) )
    (symbol (symbolRef "GND_1_N") (refDesRef "GND7") (partNum 1) (pt 1000 4400) (rotation 270.0) )
    (symbol (symbolRef "Resistor_1_N") (refDesRef "R?") (partNum 1) (pt 3100 5600) (rotation 90.0)
      (attr "RefDes" "R?" (pt 30 210) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "TC1" "0" (pt -30 420) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "TC2" "0" (pt -30 420) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "SimulationGenericCE9" "True" (pt -30 420) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Value" "10K" (pt 30 110) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Comment" "Resistor" (pt -30 420) (textStyleRef "(PartStyle)") (constraintUnits string) )
    )
  )
  (sheet "691137710002" (sheetNum 2)
    (fieldSetRef "(Default)")
    (line (pt 200 -200) (pt 200 100) (width 10) )
    (line (pt 200 -200) (pt 600 -200) (width 10) )
    (line (pt 200 100) (pt 600 100) (width 10) )
    (line (pt 600 100) (pt 600 -200) (width 10) )
  )
  (sheet "TS02_66_43_BK_100_LCR_D" (sheetNum 3)
    (fieldSetRef "(Default)")
    (line (pt 200 -200) (pt 200 100) (width 10) )
    (line (pt 200 -200) (pt 1000 -200) (width 10) )
    (line (pt 200 100) (pt 1000 100) (width 10) )
    (line (pt 1000 100) (pt 1000 -200) (width 10) )
  )
  (schematicPrintSettings
    (sheetList
      (sheetRef 2)
    )
  )
  (programState
    (gridState
      (currentAbsGrid "100mil")
      (currentRelGrid "100mil")
      (isAbsoluteGrid True)
      (isDottedGrid True)
      (isVisibleGrid True)
      (isPromptForRel False)
    )
    (ecoState (ecoRecording False))
    (currentTextStyle "(Default)")
  )
)
