// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKRbOpASqmH7ml20bMhHQI2AeWcMLv7Vs',
    appId: '1:1038025063957:web:be724e544c06e85b8b581c',
    messagingSenderId: '1038025063957',
    projectId: 'amp-controller-5b6e1',
    authDomain: 'amp-controller-5b6e1.firebaseapp.com',
    storageBucket: 'amp-controller-5b6e1.firebasestorage.app',
    measurementId: 'G-1M6M1H1PW9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5ppYUhotQ4lvYO09SF5DXqxSz1conmWo',
    appId: '1:1038025063957:android:91ce47a46637d0448b581c',
    messagingSenderId: '1038025063957',
    projectId: 'amp-controller-5b6e1',
    storageBucket: 'amp-controller-5b6e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNkx1BtKrY--g8_WHd2yKwFzMYoSmadf4',
    appId: '1:1038025063957:ios:a54f2eec32bf9bd28b581c',
    messagingSenderId: '1038025063957',
    projectId: 'amp-controller-5b6e1',
    storageBucket: 'amp-controller-5b6e1.firebasestorage.app',
    androidClientId: '1038025063957-i537nd78pbrfe6uoir6c2gsntdjqcgc5.apps.googleusercontent.com',
    iosClientId: '1038025063957-b2p82sqn53b9mmd1acooi4dp37d817cj.apps.googleusercontent.com',
    iosBundleId: 'com.example.ampController',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNkx1BtKrY--g8_WHd2yKwFzMYoSmadf4',
    appId: '1:1038025063957:ios:a54f2eec32bf9bd28b581c',
    messagingSenderId: '1038025063957',
    projectId: 'amp-controller-5b6e1',
    storageBucket: 'amp-controller-5b6e1.firebasestorage.app',
    androidClientId: '1038025063957-i537nd78pbrfe6uoir6c2gsntdjqcgc5.apps.googleusercontent.com',
    iosClientId: '1038025063957-b2p82sqn53b9mmd1acooi4dp37d817cj.apps.googleusercontent.com',
    iosBundleId: 'com.example.ampController',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKRbOpASqmH7ml20bMhHQI2AeWcMLv7Vs',
    appId: '1:1038025063957:web:1abea23194783c9b8b581c',
    messagingSenderId: '1038025063957',
    projectId: 'amp-controller-5b6e1',
    authDomain: 'amp-controller-5b6e1.firebaseapp.com',
    storageBucket: 'amp-controller-5b6e1.firebasestorage.app',
    measurementId: 'G-3CH3Q2BS46',
  );

}